#!/usr/bin/env ruby
ARGV[0] or "give me a json to convert to csv!"

require 'csv'
require 'set'
require 'json'

blob = JSON.parse(IO.read(ARGV[0]))

found_headers = Set.new
blob.each do |_, v|
  found_headers += v.keys
end
found_headers = found_headers.to_a

puts (['k'] + found_headers).to_csv

blob.each do |k, v|
  memo = v.values_at(*found_headers).map do |vv|
    case vv
    when Hash
      raise "unsupported Hash #{v.inspect}"
    when Array
      # not using to_csv
      vv.map(&:strip).join ','
    else
      vv
    end
  end
  puts ([k] + memo).to_csv
end
